# Generated by Django 5.0.2 on 2024-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
