# Generated by Django 5.0.2 on 2024-02-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'verybad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'prefect')], max_length=15, verbose_name='your score'),
        ),
    ]
